### ISSUE TITLE
Getting error when calling StatViewAssistant

### ISSUE THREAD

**Issue by agawande** [OpenIxia/ixnetwork_restpy#3]
IxNetwork: 8.42.1250.2 EA
Python: 3.7.3

Getting the following error when calling:
traffic_statistics = StatViewAssistant(ixNetwork, 'Traffic Item Statistics')

```
Traceback (most recent call last):
  File "Ixia\ixnetwork_restpy\base.py", line 118, in _get_attribute
    return self._properties[name]
  File "Ixia\ixnetwork_restpy\base.py", line 104, in _properties
    return self._object_properties[self._index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Ixia\test-high-level.py", line 74, in <module>
    traffic_statistics = StatViewAssistant(ixNetwork, 'Traffic Item Statistics')
  File "Ixia\ixnetwork_restpy\assistants\statistics\statviewassistant.py", line 93, in __init__
    self._is_view_ready
  File "Ixia\ixnetwork_restpy\assistants\statistics\statviewassistant.py", line 143, in _is_view_ready
    if self._View.Data.IsReady is True:
  File "Ixia\ixnetwork_restpy\testplatform\sessions\ixnetwork\statistics\view\data\data.py", line 161, in IsReady
    return self._get_attribute('isReady')
  File "Ixia\ixnetwork_restpy\base.py", line 120, in _get_attribute
    raise NotFoundError('The attribute %s is not in the internal list of object dicts. (%s)' % (name, e))
ixnetwork_restpy.errors.NotFoundError: The attribute isReady is not in the internal list of object dicts. (list index out of range)
```

Thanks.

**Comment by agawande** [comment]
Never mind, it works when using https://pypi.org/project/IxNetRestApi/
