### ISSUE TITLE
InstanceId is not a string

### ISSUE THREAD

**Issue by Oggie23** [OpenIxia/ixnetwork_restpy#73]
We did an update of our IxNetwork client and Chassis and we're now getting an error when updating the traffic config stack field.  The version is 9.20.2112.6.

Using the example code in the Readme:

```python
destination_mac = traffic_config.Stack.find(StackTypeId='ethernet').Field.find(FieldTypeId='ethernet.header.destinationAddress')
destination_mac.update(ValueType='valueList', ValueList=['00:00:fa:ce:fa:ce', '00:00:de:ad:be:ef'], TrackingEnabled=True)
```

The line where we update the destination_mac is throwing the following error:

```python
System.Exception: InstanceId is not a string
   at SDMCsLib.SDMObjIdPiece.GetIdAsString()
   at IxNetwork.Traffic2.Publishers.StackFieldHandler.Find(EnterExitSingleObjectHandler_EnterArgs args)
   at SDMHelpers.WalkContext.walkTo(SDMObjId objid, Hashtable idMapResponse, EnterReason reason)
   at SDMHelpers.SimplePublisher.Commit(ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitMessages, SDMSandbox track)
   at SDMCsLib.SDMPeer.commitPiece(ArrayList deltasForPublisher, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique)
   at SDMCsLib.SDMPeer.SANDBOX_DoCommit(Int32 eventMatch, ArrayList commitDeltasRequest, Hashtable idMapResponse, ArrayList commitExceptionsResponse, Version version, Boolean bCommitIfUnique, eSandboxType sandboxType)
   at SDMCsLib.SDMSandbox.DoCommit(Boolean bCommitIfUnique, eSandboxType sandboxType)
   at SDMCsLib.RestService.SdmSandbox.Commit(Boolean isAddOperation)
   at SDMCsLib.RestService.SdmObject.Patch()
   at SDMCsLib.RestService.V1ObjectController.Patch(String path)
        Current Server Errors/Warnings:
        05/16/2023 16:17:30 [WARNING] [Traffic Generate required] The Traffic Item was modified. Please perform a Traffic Generate to update the associated traffic Flow Groups
```

It seems like InstanceId (whatever that is) was a string before, but not anymore?

**Comment by ajbalogh** [comment]
@Oggie23  This bug is fixed in 9.20 Update 2 and above. Can you apply the 9.20 Update 3 and try the script again?

**Comment by Oggie23** [comment]
Ohhh!  In that case, I have to wait for new license in order to apply Update 3.  I will update as soon as possible and post results.  Thanks!

**Comment by cruise-bryan-murdock** [comment]
@ajbalogh we are on Web Platform 9.21.2.3 and we are seeing this bug.

**Comment by ajbalogh** [comment]
> I don't see updates available for Web Platform, but I do see an update available for Web Edition. Is that what we need to update?

@cruise-bryan-murdock  Yes the web edition is what needs to be updated.

**Comment by Vibaswan** [comment]
This has been fixed
